name: create

on:
  workflow_dispatch:
  push:
    tags:
      - '**'
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
       run:
         shell: bash
         working-directory: ./tf
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "${{vars.TERRAFORM_VERSION}}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        env:
          TF_VAR_bucket_name: ${{ vars.AWS_BUCKET_TERRAFORM }}
        run: terraform plan -input=false
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        env:
          TF_VAR_bucket_name: ${{ vars.AWS_BUCKET_TERRAFORM }}
        run: terraform apply -input=false -auto-approve
