name: destroy

on:
  workflow_dispatch:
  
jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "${{vars.TERRAFORM_VERSION}}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_TF_STATE }}"

      - name: Terraform Plan
        id: plan
        env:
          TF_VAR_bucket_name: ${{ secrets.AWS_BUCKET_TF_STATE }}
        run: terraform plan -input=false
        continue-on-error: true

      - name: Terraform Destroy
        if: github.ref == 'refs/heads/main'
        env:
          TF_VAR_bucket_name: ${{ secrets.AWS_BUCKET_TF_STATE }}
        run: terraform destroy -input=false -auto-approve